# Build Imp City with gradle

name: Java CI with Gradle

on:
  workflow_dispatch:


#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5
     
    - name: Execute Gradle build
      run: ./gradlew jar

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: app/build/libs/app.jar
        asset_name: app.jar
        tag: Nightly
        overwrite: true      
