# Build Imp City with gradle

name: Java CI with Gradle

on:
  workflow_dispatch:


#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5
     
    - name: Execute Gradle build
      run: ./gradlew jar

    - name: Build release package
      run: |
        wget https://github.com/Varkalandar/imp_city/releases/download/v0.28/imp_city_v0.28-linux.7z
        7z x imp_city_v0.28-linux.7z
        ls -l
        cp -v app/build/libs/app.jar imp_city_v0.28-linux/app/lib/
        mv imp_city_v0.28-linux imp_city_nightly-linux
        7z a imp_city_nightly-linux.7z imp_city_nightly-linux
        
    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: imp_city_nightly-linux.7z
        asset_name: app.jar
        tag: Nightly
        overwrite: true      
